# GitHub Actions workflow 文件
# 文件名: .github/workflows/update-iptv.yml

name: 自动更新 IPTV 源

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  update-iptv:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v3

      - name: 下载并处理 IPTV 文件
        run: |
          # 下载原始 m3u 文件
          curl -s -o original.m3u https://sub.ottiptv.cc/iptv.m3u

          grep -v -F \
          -e '#EXTINF:-1 tvg-name="4K60PSDR-H264-AAC测试" tvg-logo="https://cdn.jsdelivr.net/gh/feiyang666999/testvideo/tg.jpg" group-title="4K频道",4K60PSDR-H264-AAC测试' \
          -e 'https://cdn.jsdelivr.net/gh/feiyang666999/testvideo/sdr4kvideo/playlist.m3u8' \
          -e '#EXTINF:-1 tvg-name="4K60PHLG-HEVC-EAC3测试" tvg-logo="https://cdn.jsdelivr.net/gh/feiyang666999/testvideo/tg.jpg" group-title="4K频道",4K60PHLG-HEVC-EAC3测试' \
          -e 'https://cdn.jsdelivr.net/gh/feiyang666999/testvideo/hlg4kvideo/playlist.m3u8' \
          -e '#EXTINF:-1,tvg-id="重温经典" tvg-name="重温经典" tvg-logo="https://11.112114.xyz/logo/重温经典.png" group-title="其他",重温经典' \
          -e 'https://gdcucc.v1.mk/gdcucc/cwjd.m3u8' \
          -e '#EXTINF:-1,tvg-id="五星体育" tvg-name="五星体育" tvg-logo="https://11.112114.xyz/logo/五星体育.png" group-title="其他",五星体育' \
          -e 'https://gdcucc.v1.mk/gdcucc/wxty.m3u8' \
          -e '#EXTINF:-1,tvg-id="中国教育1台" tvg-name="中国教育1台" tvg-logo="https://11.112114.xyz/logo/中国教育1台.png" group-title="其他",中国教育电视台-MCP' \
          -e 'https://mursor.ottiptv.cc/mcp/cetv1.m3u8' \
          original.m3u > IPTV.m3u

          mkdir -p m3u

          mv IPTV.m3u m3u/IPTV.m3u

          rm original.m3u

      - name: 提交并推送文件
        run: |
          # 配置 git 用户
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git add m3u/IPTV.m3u
          
          if git diff --staged --quiet; then
            echo "没有检测到文件变动，无需提交。"
          else
            git commit -m "chore: 自动更新 IPTV源 (`date +'%Y-%m-%d %H:%M:%S' UTC`)"
            git push
          fi
