name: 自动更新 IPTV 精简源

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4

      - name: 下载源 IPTV 文件
        run: curl -s -L -o source.m3u https://sub.ottiptv.cc/iptv.m3u

      - name: 根据模板模糊匹配生成 IPTV 文件
        run: |
          mkdir -p m3u

          awk '
            function normalize(name) {
              s = name
              s = tolower(s)
              gsub(/[ \t\-_]/, "", s)
              gsub(/hd|fhd|uhd|4k|高清|超清|标清|频道|综合/, "", s)
              return s
            }

            BEGIN {
              FS = ","
            }
            FNR==NR {
              if ($0 ~ /^#EXTINF/) {
                original_name = $NF
                getline url
                if (original_name != "" && url != "") {
                  source_urls[normalize(original_name)] = url
                }
              }
              next
            }
            {
              if ($0 ~ /^#EXTINF/) {
                print $0
                
                template_name = $NF
                
                getline placeholder_url

                norm_template_name = normalize(template_name)
                
                best_match_key = ""
                for (norm_source_name in source_urls) {
                  if (index(norm_source_name, norm_template_name)) {
                    if (best_match_key == "" || length(norm_source_name) < length(best_match_key)) {
                      best_match_key = norm_source_name
                    }
                  }
                }

                if (best_match_key != "") {
                  print source_urls[best_match_key]
                } else {
                  print placeholder_url
                  print "警告: 在源文件中未能模糊匹配到频道 [" template_name "]" > "/dev/stderr"
                }
              } else {
                print $0
              }
            }
          ' source.m3u iptv_template/IPTV_Template.m3u > m3u/IPTV_Simple.m3u

          echo "IPTV 文件已根据模板成功生成到 m3u/IPTV_Simple.m3u"

      - name: 提交并推送文件
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add m3u/IPTV_Simple.m3u
          if git diff --staged --quiet; then
            echo "文件内容无变化，无需提交。"
          else
            git commit -m "feat: 自动更新 IPTV 列表 (Simple) ($(date -u +'%Y-%m-%d %H:%M:%S UTC'))"
            git push
          fi
